package cli

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsLoopbackBase(t *testing.T) {
	tests := []struct {
		base string
		want bool
	}{
		{"", true}, // empty means "use the compiled-in default", which is loopback
		{"http://127.0.0.1:7337", true},
		{"http://localhost:7337", true},
		{"http://[::1]:7337", true},
		{"http://192.168.0.111:7337", false},
		{"http://159.203.184.97:7337", false},
		{"https://otter.example.com", false},
		{"not a url", false},
	}
	for _, tc := range tests {
		if got := isLoopbackBase(tc.base); got != tc.want {
			t.Errorf("isLoopbackBase(%q) = %v, want %v", tc.base, got, tc.want)
		}
	}
}

// readEnvValue must handle the file `otter deploy` writes and nothing more.
func TestReadEnvValue(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shopify-to-salesforce.env")
	body := `# Generated by otter deploy
OTTER_API_TOKEN=tok_abc123

# --- secrets ---
SHOPIFY_CLIENT_ID=xyz
`
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	if got := readEnvValue(path, "OTTER_API_TOKEN"); got != "tok_abc123" {
		t.Errorf("OTTER_API_TOKEN = %q, want tok_abc123", got)
	}
	if got := readEnvValue(path, "SHOPIFY_CLIENT_ID"); got != "xyz" {
		t.Errorf("SHOPIFY_CLIENT_ID = %q, want xyz", got)
	}
	if got := readEnvValue(path, "ABSENT"); got != "" {
		t.Errorf("an absent key returned %q, want empty", got)
	}
	if got := readEnvValue(filepath.Join(dir, "missing.env"), "OTTER_API_TOKEN"); got != "" {
		t.Errorf("a missing file returned %q, want empty", got)
	}
}

// localHostToken must never read the local host's file for a remote API. A
// tunnel forwards a remote daemon to 127.0.0.1, and presenting the wrong token
// would be more confusing than a clear 401.
func TestLocalHostTokenOnlyForLoopback(t *testing.T) {
	if got := localHostToken("http://159.203.184.97:7337"); got != "" {
		t.Errorf("a remote API produced a local token %q", got)
	}
	if got := localHostToken("http://192.168.0.111:7337"); got != "" {
		t.Errorf("a LAN API produced a local token %q", got)
	}
}

// On a loopback API the token comes from the daemon's own environment file,
// which is what removes the copy-and-paste on the host.
func TestLocalHostTokenReadsTheEnvFile(t *testing.T) {
	dir := t.TempDir()
	// Point EnvDir at a temporary directory for the test.
	previous := envDirForTest
	envDirForTest = dir
	t.Cleanup(func() { envDirForTest = previous })

	if err := os.WriteFile(filepath.Join(dir, "counter.env"), []byte("OTTER_API_TOKEN=from_file\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if got := localHostToken(""); got != "from_file" {
		t.Errorf("localHostToken() = %q, want from_file", got)
	}
	if got := localHostToken("http://127.0.0.1:7337"); got != "from_file" {
		t.Errorf("localHostToken(loopback) = %q, want from_file", got)
	}
}

// An explicit flag or environment variable must still win: the file is a
// convenience, not an override.
func TestExplicitTokenBeatsTheEnvFile(t *testing.T) {
	dir := t.TempDir()
	previous := envDirForTest
	envDirForTest = dir
	t.Cleanup(func() { envDirForTest = previous })

	if err := os.WriteFile(filepath.Join(dir, "counter.env"), []byte("OTTER_API_TOKEN=from_file\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	// No flag and no environment variable: the file is used.
	if got := (globals{}).client().Token; got != "from_file" {
		t.Errorf("token = %q, want the value from the env file", got)
	}

	// An explicit --token wins over the file.
	if got := (globals{token: "explicit"}).client().Token; got != "explicit" {
		t.Errorf("token = %q, want the explicit value", got)
	}
}
