package deploy

import (
	"fmt"
	"sort"
	"strings"
)

// This file renders everything that lands on the remote host: the systemd
// unit, the integration environment files, and the shell scripts that install
// them. Nothing here reads the network, which is what makes it cheap to test.

// UnitFile renders the systemd unit for otterd.
//
// A few choices here are deliberate rather than incidental:
//
//   - Restart=always plus the daemon's own crash recovery means a binary swap
//     and a restart is the entire upgrade procedure. Interrupted runs are
//     re-queued on startup, so a deploy never drops work that was in flight.
//   - The API binds loopback. systemd carries the token check, not a firewall;
//     the CLI reaches the API through an SSH tunnel.
//   - The unit never writes to the data directory. The database and the
//     extracted Python SDK survive every deploy untouched.
func UnitFile(t Target) string {
	var b strings.Builder

	b.WriteString("# Generated by `otter deploy`. Edits are overwritten on the next deploy.\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=Otter runtime for the %s workspace\n", t.WorkspaceName())
	b.WriteString("Documentation=https://github.com/tkoizumi/otter\n")
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")

	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "User=%s\n", t.RunAsUser)
	fmt.Fprintf(&b, "Group=%s\n", t.RunAsUser)
	fmt.Fprintf(&b, "WorkingDirectory=%s\n", t.WorkspaceDir())
	fmt.Fprintf(&b, "ExecStart=%s --integrations %s --data %s --listen %s --log-format json\n",
		t.BinaryPath(), t.IntegrationsDir(), t.DataDir, t.Listen)
	// Two files, in precedence order: systemd applies a later EnvironmentFile
	// over an earlier one, so daemon settings load first and the credentials
	// every integration shares load second.
	//
	// Both are optional. systemd tolerates a missing EnvironmentFile with a
	// leading dash, which keeps a deployment that configures nothing beyond its
	// manifests working with no extra files at all.
	fmt.Fprintf(&b, "EnvironmentFile=-%s\n", t.DaemonEnvFilePath())
	fmt.Fprintf(&b, "EnvironmentFile=-%s\n", t.SharedEnvFilePath())
	b.WriteString("Restart=always\n")
	b.WriteString("RestartSec=2\n")
	// SIGTERM starts the daemon's graceful shutdown: running integrations get
	// their grace period, then the daemon exits and systemd starts it again.
	b.WriteString("KillSignal=SIGTERM\n")
	b.WriteString("TimeoutStopSec=45\n\n")

	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}

// SharedEnvFile renders the environment block every integration inherits.
//
// The daemon's environment is the only channel secrets travel through: the
// child process inherits it, the API never returns it, and `otter inspect`
// cannot show it. systemd sources this file with EnvironmentFile=, so values
// must stay shell-compatible: one KEY=value per line, no export, no
// interpolation.
//
// There is one of these rather than one per integration because the secrets
// store is the daemon's single environment anyway: a per-integration file
// isolated nothing, and it made rotating one credential an N-file edit.
func SharedEnvFile(apiToken string, secrets map[string]string) string {
	var b strings.Builder

	b.WriteString("# Generated by `otter deploy`. Mode 0600, root owned.\n")
	b.WriteString("# Credentials shared by every integration. An integration receives only\n")
	b.WriteString("# the keys its own manifest declares. Re-run `otter deploy` to refresh;\n")
	b.WriteString("# do not edit by hand.\n\n")

	if apiToken != "" {
		b.WriteString("OTTER_API_TOKEN=" + apiToken + "\n\n")
	}

	b.WriteString("# --- shared secrets ---\n")
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, secrets[k])
	}
	return b.String()
}

// InstallScript is the remote bootstrap. It converges the host onto the
// desired state: the service account exists, the directories exist with the
// right modes, the unit file is current, and the daemon is running the binary
// that was just pushed. The unit file is appended to the script as a heredoc,
// so the whole converge is one round trip.
//
// It is safe to run repeatedly, and it never touches the data directory: that
// directory holds the sync watermarks and the run history, the two things a
// deploy must not lose.
func InstallScript(t Target) string {
	return PrepareScript(t) + ClaimOwnershipScript(t) + ActivateScript(t)
}

// PrepareScript creates the service account and the directory layout the rest
// of the deploy depends on.
//
// It runs before the push. rsync creates its destination directory but not the
// levels above it, and a workspace lives two levels inside the install root, so
// /opt/otter/workspaces/<name> has to exist before the first file is sent.
// Ownership is claimed again afterwards, by ClaimOwnershipScript.
func PrepareScript(t Target) string {
	return `set -e
SERVICE=` + ShellQuote(t.ServiceUnit()) + `
RUN_AS=` + ShellQuote(t.RunAsUser) + `
REMOTE_DIR=` + ShellQuote(t.RemoteDir) + `
WORKSPACES_ROOT=` + ShellQuote(t.WorkspacesRoot()) + `
WORKSPACE_DIR=` + ShellQuote(t.WorkspaceDir()) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
ENV_DIR=` + ShellQuote(t.EnvDir()) + `
UNIT=` + ShellQuote(t.UnitPath()) + `

# 1. The service account. Guarding on ` + "`getent`" + ` rather than a hardcoded
# uid keeps an existing account intact.
if ! getent group "$RUN_AS" >/dev/null 2>&1; then
  groupadd --system "$RUN_AS"
fi
if ! id -u "$RUN_AS" >/dev/null 2>&1; then
  useradd --system --gid "$RUN_AS" --home-dir "$REMOTE_DIR" --no-create-home --shell /usr/sbin/nologin "$RUN_AS"
fi

# 2. Layout. Each workspace owns a directory; nothing here is shared with
#    another workspace except the account itself.
install -d -m 0755 "$REMOTE_DIR" "$WORKSPACES_ROOT"
install -d -m 0755 -o "$RUN_AS" -g "$RUN_AS" "$WORKSPACE_DIR" "$WORKSPACE_DIR/bin" "$WORKSPACE_DIR/integrations" "$WORKSPACE_DIR/tools"
install -d -m 0700 -o "$RUN_AS" -g "$RUN_AS" "$DATA_DIR"
install -d -m 0700 "$ENV_DIR"

`
}

// ClaimOwnershipScript hands this workspace's files to the service account.
//
// It runs *after* the push, not before: rsync writes as the login user, so a
// tree pushed by root would be unreadable to the daemon and the service account
// could not write the .otter-id marker every integration needs.
//
// The data directory itself is excluded because it is already correct;
// recursively chowning a live SQLite database on every deploy would be
// pointless and risky. Its derived contents are handled separately, since
// preparation and releases write into them as root.
func ClaimOwnershipScript(t Target) string {
	return `set -e
RUN_AS=` + ShellQuote(t.RunAsUser) + `
WORKSPACE_DIR=` + ShellQuote(t.WorkspaceDir()) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `

for dir in bin integrations lib tools; do
  [ -e "$WORKSPACE_DIR/$dir" ] && chown -R "$RUN_AS:$RUN_AS" "$WORKSPACE_DIR/$dir"
done
chown "$RUN_AS:$RUN_AS" "$WORKSPACE_DIR" 2>/dev/null || true
chown "$RUN_AS:$RUN_AS" "$DATA_DIR" 2>/dev/null || true
for derived in .releases cache python; do
  [ -e "$DATA_DIR/$derived" ] && chown "$RUN_AS:$RUN_AS" "$DATA_DIR/$derived" 2>/dev/null || true
done
if [ -d "$DATA_DIR/.releases" ]; then
  find "$DATA_DIR/.releases" -exec chown "$RUN_AS:$RUN_AS" {} + 2>/dev/null || true
fi
if [ -d "$DATA_DIR/environments" ]; then
  chown "$RUN_AS:$RUN_AS" "$DATA_DIR/environments" 2>/dev/null || true
  for envdir in "$DATA_DIR"/environments/*/; do
    [ -d "$envdir" ] || continue
    chown "$RUN_AS:$RUN_AS" "$envdir" 2>/dev/null || true
    for sub in bin lib include share pyvenv.cfg otter-ready.json; do
      [ -e "$envdir$sub" ] || continue
      if [ -L "$envdir$sub" ]; then
        chown -h "$RUN_AS:$RUN_AS" "$envdir$sub" 2>/dev/null || true
      else
        chown -R "$RUN_AS:$RUN_AS" "$envdir$sub" 2>/dev/null || true
      fi
    done
  done
fi
`
}

// CLIDispatcherPath is where the host-wide `otter` entry point is installed.
const CLIDispatcherPath = "/usr/local/bin/otter"

// dispatcherMarker identifies a file this tool wrote, so a destroy can tell its
// own dispatcher from something an operator put there.
const dispatcherMarker = "# otter-deploy-dispatcher"

// DispatcherFile is the host-wide `otter` entry point.
//
// Each workspace keeps its own CLI, which is right for isolation and wrong for
// an operator: the host is where someone lands when a sync is failing, and
// retyping <workspace>/bin/otter from memory is not something anyone does.
//
// It is a dispatcher rather than a symlink because a symlink can only name one
// workspace. The script finds the workspace the working directory belongs to --
// the same rule every other otter command uses -- loads that workspace's token
// so the API does not answer 401, and only falls back to a host-wide answer
// when there is exactly one workspace to mean.
func DispatcherFile(t Target) string {
	return `#!/bin/sh
` + dispatcherMarker + `
# Runs the CLI of the workspace this directory belongs to.
ROOT=` + ShellQuote(t.WorkspacesRoot()) + `

ws=""
dir="$PWD"
while [ "$dir" != "/" ]; do
  if [ -x "$dir/bin/otter" ] && [ -d "$dir/.otter" ]; then
    ws="$dir"
    break
  fi
  dir=$(dirname "$dir")
done

if [ -n "$ws" ]; then
  # The daemon requires its bearer token even on loopback. Reading it here is
  # what makes a bare "otter runs" work for whoever can read the file; anyone
  # else still gets the CLI's own hint.
  envfile="/etc/otter/workspaces/$(basename "$ws").env"
  if [ -r "$envfile" ]; then
    token=$(grep -m1 '^OTTER_API_TOKEN=' "$envfile" 2>/dev/null | cut -d= -f2-)
    if [ -n "$token" ]; then
      OTTER_API_TOKEN="$token"
      export OTTER_API_TOKEN
    fi
  fi
  exec "$ws/bin/otter" "$@"
fi

found=""
for candidate in "$ROOT"/*/bin/otter; do
  [ -x "$candidate" ] || continue
  if [ -n "$found" ]; then
    echo "otter: not inside a workspace, and this host holds several:" >&2
    for other in "$ROOT"/*/; do
      [ -d "$other" ] && echo "  ${other%/}" >&2
    done
    echo "otter: cd into one first" >&2
    exit 1
  fi
  found="$candidate"
done

if [ -n "$found" ]; then
  exec "$found" "$@"
fi

echo "otter: no workspace on this host (looked in $ROOT)" >&2
exit 1
`
}

// ActivateScript writes the unit, locks down secrets and restarts the service.
//
// It is the last thing a deploy does: everything before it can fail without
// disturbing the running daemon.
func ActivateScript(t Target) string {
	var b strings.Builder

	script := `set -e
SERVICE=` + ShellQuote(t.ServiceUnit()) + `
RUN_AS=` + ShellQuote(t.RunAsUser) + `
REMOTE_DIR=` + ShellQuote(t.RemoteDir) + `
WORKSPACE_DIR=` + ShellQuote(t.WorkspaceDir()) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
ENV_DIR=` + ShellQuote(t.EnvDir()) + `
SHARED_ENV=` + ShellQuote(t.SharedEnvFilePath()) + `
DAEMON_ENV=` + ShellQuote(t.DaemonEnvFilePath()) + `
UNIT=` + ShellQuote(t.UnitPath()) + `

# The unit file, written atomically by the redirect.
cat > "$UNIT" <<'OTTER_UNIT_EOF'
`
	b.WriteString(script)
	b.WriteString(UnitFile(t))
	b.WriteString(`OTTER_UNIT_EOF
chmod 0644 "$UNIT"

# Lock down this workspace's secrets. Only its own two files: the environment
# directory is shared by every workspace on the host, and chmod-ing the whole
# directory would touch files this deploy does not own.
chmod 0755 "$WORKSPACE_DIR/bin/otter" 2>/dev/null || true
chmod 0600 "$SHARED_ENV" "$DAEMON_ENV" 2>/dev/null || true

# A host-wide otter entry point, as a dispatcher rather than a symlink: one
# symlink can only name one workspace, and this host may hold several.
install -d -m 0755 /usr/local/bin
cat > ` + ShellQuote(CLIDispatcherPath) + ` <<'OTTER_DISPATCH_EOF'
` + DispatcherFile(t) + `OTTER_DISPATCH_EOF
chmod 0755 ` + ShellQuote(CLIDispatcherPath) + `

systemctl daemon-reload
systemctl enable "$SERVICE" >/dev/null 2>&1 || true
systemctl restart "$SERVICE"
`)
	return b.String()
}

// ServiceStatusScript reports whether the unit is active, then prints the tail
// of its journal so a failed start explains itself instead of timing out.
func ServiceStatusScript(t Target) string {
	return `SERVICE=` + ShellQuote(t.ServiceUnit()) + `
echo "unit: $(systemctl is-active "$SERVICE" 2>/dev/null || true)"
if ! systemctl is-active --quiet "$SERVICE"; then
  echo "--- last 25 journal lines ---"
  journalctl -u "$SERVICE" -n 25 --no-pager 2>/dev/null || true
  exit 1
fi
`
}

// ReleaseScript stages, prepares and activates a release for each integration
// on the host.
//
// It runs after the sources land and before the daemon restarts. Order matters
// twice over: preparation must not happen underneath a running attempt, and a
// failure here must leave the previous release active, which is why activation
// is the last thing `otter release` does rather than something this script
// performs.
//
// Shared code is not named here. Each manifest declares its own python.path,
// and the release captures exactly those trees, placed relative to the same base
// as the integration, so the layout lives in one place instead of being repeated
// on this command line.
//
// The --integrations root still matters to that placement: it is the discovery
// root the release scans, and the base it computes takes that root in. Passing
// the install root instead would make the discovery scan the binaries, tools
// and data directories for manifests.
//
// Integrations are named one by one rather than released with --all so each
// release reports its own failure against its own name in the deploy log.
func ReleaseScript(t Target, integrations []string, uvPath string) string {
	script := `set -e
RUN_AS=` + ShellQuote(t.RunAsUser) + `
WORKSPACE_DIR=` + ShellQuote(t.WorkspaceDir()) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
CLI=` + ShellQuote(t.CLIPath()) + `
test -x "$CLI" || { echo "otter: missing $CLI" >&2; exit 1; }
# The data directory is prepared beforehand; releases only write inside it.
#
# Run from a directory the service account can traverse. A non-login ssh
# command starts in the login user's home -- /root, mode 0700 -- and the CLI
# resolves its workspace from the working directory even when every path it was
# given is absolute, so inheriting /root fails with "stat .: permission denied".
cd "$WORKSPACE_DIR"
`

	runAs := ""
	if t.RunAsUser != "root" {
		script += `command -v runuser >/dev/null 2>&1 || { echo "otter: runuser is required to release as $RUN_AS" >&2; exit 1; }
`
		runAs = `runuser -u "$RUN_AS" -- `
	}

	for _, name := range integrations {
		command := runAs + `"$CLI" release` +
			" --integrations " + ShellQuote(t.IntegrationsDir()) +
			" --data " + ShellQuote(t.DataDir)
		if uvPath != "" {
			command += " --uv " + ShellQuote(uvPath)
		}
		// The destination path, not a bare basename. A basename is read as a
		// label, so a directory whose name differs from the manifest's would
		// resolve to the wrong integration -- or to none -- and an identity
		// would be registered against the wrong tree.
		command += " " + ShellQuote(t.IntegrationsDir()+"/"+name)

		script += "echo " + ShellQuote("releasing "+name) + "\n" + command + "\n"
	}
	// Each release reported success above, and a successful release is already
	// active; there is nothing further to switch.
	return script
}

// BindingsScript prints the destination registry as JSON.
//
// It reads the registry rather than the API so it works when the runtime is
// stopped, and it runs as the service user because the data directory is
// owner-only. The integrations root is passed explicitly: the host has no
// workspace marker of its own.
func BindingsScript(t Target) string {
	runAs := ""
	if t.RunAsUser != "root" {
		runAs = `runuser -u ` + ShellQuote(t.RunAsUser) + ` -- `
	}
	// The cd runs in the ssh shell, before privileges are dropped, for the same
	// reason the release script does it: the service account must not inherit a
	// working directory it cannot traverse.
	return "cd " + ShellQuote(t.WorkspaceDir()) + " && " +
		runAs + ShellQuote(t.CLIPath()) + " identity list --json" +
		" --data " + ShellQuote(t.DataDir) +
		" --integrations " + ShellQuote(t.IntegrationsDir())
}

// DestroyScript removes the unit and, unless keepData, the data directory.
// Losing the data directory means losing every integration's watermark, so the
// CLI requires an explicit flag before this runs without keeping it.
func DestroyScript(t Target, keepData bool) string {
	script := `set -e
SERVICE=` + ShellQuote(t.ServiceUnit()) + `
WORKSPACES_ROOT=` + ShellQuote(t.WorkspacesRoot()) + `
WORKSPACE_DIR=` + ShellQuote(t.WorkspaceDir()) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
SHARED_ENV=` + ShellQuote(t.SharedEnvFilePath()) + `
DAEMON_ENV=` + ShellQuote(t.DaemonEnvFilePath()) + `
UNIT=` + ShellQuote(t.UnitPath()) + `

# Only this workspace's unit, environment files and directory. Every path here
# is workspace-scoped on purpose: a shared host keeps other workspaces running.
systemctl stop "$SERVICE" 2>/dev/null || true
systemctl disable "$SERVICE" >/dev/null 2>&1 || true
rm -f "$UNIT"
rm -f /etc/systemd/system/multi-user.target.wants/"$SERVICE"
systemctl daemon-reload
systemctl reset-failed "$SERVICE" 2>/dev/null || true
rm -f "$SHARED_ENV" "$DAEMON_ENV"
# The host-wide dispatcher is shared, so it only goes when this was the last
# workspace -- and only if this tool wrote it.
if [ -f ` + ShellQuote(CLIDispatcherPath) + ` ] &&
   head -n 2 ` + ShellQuote(CLIDispatcherPath) + ` | grep -q ` + ShellQuote(dispatcherMarker) + `; then
  remaining=$(ls -d "$WORKSPACES_ROOT"/*/ 2>/dev/null | wc -l)
  [ "$remaining" -eq 0 ] && rm -f ` + ShellQuote(CLIDispatcherPath) + `
fi
`
	if keepData {
		script += `# Keep the data directory and drop everything else.
find "$WORKSPACE_DIR" -mindepth 1 -maxdepth 1 ! -name ` + ShellQuote(StateDirName) + ` -exec rm -rf {} +
rm -f "$WORKSPACE_DIR/` + WorkspaceRecordName + `"
`
	} else {
		script += `rm -rf "$WORKSPACE_DIR"
`
	}
	script += `# Remove the workspaces root when this was the last one.
rmdir "$WORKSPACES_ROOT" 2>/dev/null || true
`
	return script
}
