package deploy

import (
	"fmt"
	"sort"
	"strings"
)

// This file renders everything that lands on the remote host: the systemd
// unit, the integration environment files, and the shell scripts that install
// them. Nothing here reads the network, which is what makes it cheap to test.

// UnitFile renders the systemd unit for otterd.
//
// A few choices here are deliberate rather than incidental:
//
//   - Restart=always plus the daemon's own crash recovery means a binary swap
//     and a restart is the entire upgrade procedure. Interrupted runs are
//     re-queued on startup, so a deploy never drops work that was in flight.
//   - The API binds loopback. systemd carries the token check, not a firewall;
//     the CLI reaches the API through an SSH tunnel.
//   - The unit never writes to the data directory. The database and the
//     extracted Python SDK survive every deploy untouched.
func UnitFile(t Target) string {
	var b strings.Builder

	b.WriteString("# Generated by `otter deploy`. Edits are overwritten on the next deploy.\n")
	b.WriteString("[Unit]\n")
	b.WriteString("Description=Otter runtime for Python integrations\n")
	b.WriteString("Documentation=https://github.com/tkoizumi/otter\n")
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")

	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "User=%s\n", t.RunAsUser)
	fmt.Fprintf(&b, "Group=%s\n", t.RunAsUser)
	fmt.Fprintf(&b, "WorkingDirectory=%s\n", t.RemoteDir)
	fmt.Fprintf(&b, "ExecStart=%s --integrations %s --data %s --listen %s --log-format json\n",
		t.BinaryPath(), t.IntegrationsDir(), t.DataDir, t.Listen)
	// Two files, in precedence order: systemd applies a later EnvironmentFile
	// over an earlier one, so daemon settings load first and the credentials
	// every integration shares load second.
	//
	// Both are optional. systemd tolerates a missing EnvironmentFile with a
	// leading dash, which keeps a deployment that configures nothing beyond its
	// manifests working with no extra files at all.
	fmt.Fprintf(&b, "EnvironmentFile=-%s\n", t.DaemonEnvFilePath())
	fmt.Fprintf(&b, "EnvironmentFile=-%s\n", t.SharedEnvFilePath())
	b.WriteString("Restart=always\n")
	b.WriteString("RestartSec=2\n")
	// SIGTERM starts the daemon's graceful shutdown: running integrations get
	// their grace period, then the daemon exits and systemd starts it again.
	b.WriteString("KillSignal=SIGTERM\n")
	b.WriteString("TimeoutStopSec=45\n\n")

	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}

// SharedEnvFile renders the environment block every integration inherits.
//
// The daemon's environment is the only channel secrets travel through: the
// child process inherits it, the API never returns it, and `otter inspect`
// cannot show it. systemd sources this file with EnvironmentFile=, so values
// must stay shell-compatible: one KEY=value per line, no export, no
// interpolation.
//
// There is one of these rather than one per integration because the secrets
// store is the daemon's single environment anyway: a per-integration file
// isolated nothing, and it made rotating one credential an N-file edit.
func SharedEnvFile(apiToken string, secrets map[string]string) string {
	var b strings.Builder

	b.WriteString("# Generated by `otter deploy`. Mode 0600, root owned.\n")
	b.WriteString("# Credentials shared by every integration. An integration receives only\n")
	b.WriteString("# the keys its own manifest declares. Re-run `otter deploy` to refresh;\n")
	b.WriteString("# do not edit by hand.\n\n")

	if apiToken != "" {
		b.WriteString("OTTER_API_TOKEN=" + apiToken + "\n\n")
	}

	b.WriteString("# --- shared secrets ---\n")
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, secrets[k])
	}
	return b.String()
}

// InstallScript is the remote bootstrap. It converges the host onto the
// desired state: the service account exists, the directories exist with the
// right modes, the unit file is current, and the daemon is running the binary
// that was just pushed. The unit file is appended to the script as a heredoc,
// so the whole converge is one round trip.
//
// It is safe to run repeatedly, and it never touches the data directory: that
// directory holds the sync watermarks and the run history, the two things a
// deploy must not lose.
func InstallScript(t Target) string {
	return PrepareScript(t) + ActivateScript(t)
}

// PrepareScript creates the service account and the directory layout the rest
// of the deploy depends on.
//
// It runs before secrets, before release, and before activation. Every later
// step assumes the account exists -- writing an environment file, preparing an
// environment, or taking ownership of the data directory -- so creating it is
// its own step rather than a side effect of installing the unit.
func PrepareScript(t Target) string {
	return `set -e
SERVICE=` + ShellQuote(t.ServiceUnit()) + `
RUN_AS=` + ShellQuote(t.RunAsUser) + `
REMOTE_DIR=` + ShellQuote(t.RemoteDir) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
ENV_DIR=` + ShellQuote(t.EnvDir()) + `
UNIT=` + ShellQuote(t.UnitPath()) + `

# 1. The service account. Guarding on ` + "`getent`" + ` rather than a hardcoded
# uid keeps an existing account intact.
if ! getent group "$RUN_AS" >/dev/null 2>&1; then
  groupadd --system "$RUN_AS"
fi
if ! id -u "$RUN_AS" >/dev/null 2>&1; then
  useradd --system --gid "$RUN_AS" --home-dir "$REMOTE_DIR" --no-create-home --shell /usr/sbin/nologin "$RUN_AS"
fi

# 2. Layout. The data directory is created but never written to, so its
#    contents survive the deploy.
mkdir -p "$REMOTE_DIR/bin" "$REMOTE_DIR/integrations"
install -d -m 0755 "$REMOTE_DIR"
install -d -m 0700 -o "$RUN_AS" -g "$RUN_AS" "$DATA_DIR"
install -d -m 0700 "$ENV_DIR"

# 3. Ownership of the checkout and binaries. The data directory itself is
#    excluded because it is already correct; recursively chowning a live SQLite
#    database on every deploy is pointless and risky. Its contents are handled
#    separately, since preparation and releases write into it as root.
for dir in bin integrations lib tools; do
  [ -e "$REMOTE_DIR/$dir" ] && chown -R "$RUN_AS:$RUN_AS" "$REMOTE_DIR/$dir"
done
# Derived state inside the data directory was written by root during
# preparation, so hand the derived directories over without walking the
# database: the goal is that the daemon can read its environment, not that
# every file changes owner.
chown "$RUN_AS:$RUN_AS" "$DATA_DIR" 2>/dev/null || true
for derived in .releases cache python; do
  [ -e "$DATA_DIR/$derived" ] && chown "$RUN_AS:$RUN_AS" "$DATA_DIR/$derived" 2>/dev/null || true
done
if [ -d "$DATA_DIR/.releases" ]; then
  find "$DATA_DIR/.releases" -exec chown "$RUN_AS:$RUN_AS" {} + 2>/dev/null || true
fi
if [ -d "$DATA_DIR/environments" ]; then
  chown "$RUN_AS:$RUN_AS" "$DATA_DIR/environments" 2>/dev/null || true
  for envdir in "$DATA_DIR"/environments/*/; do
    [ -d "$envdir" ] || continue
    chown "$RUN_AS:$RUN_AS" "$envdir" 2>/dev/null || true
    for sub in bin lib include share pyvenv.cfg otter-ready.json; do
      [ -e "$envdir$sub" ] || continue
      if [ -L "$envdir$sub" ]; then
        chown -h "$RUN_AS:$RUN_AS" "$envdir$sub" 2>/dev/null || true
      else
        chown -R "$RUN_AS:$RUN_AS" "$envdir$sub" 2>/dev/null || true
      fi
    done
  done
fi
`
}

// ActivateScript writes the unit, locks down secrets and restarts the service.
//
// It is the last thing a deploy does: everything before it can fail without
// disturbing the running daemon.
func ActivateScript(t Target) string {
	var b strings.Builder

	script := `set -e
SERVICE=` + ShellQuote(t.ServiceUnit()) + `
RUN_AS=` + ShellQuote(t.RunAsUser) + `
REMOTE_DIR=` + ShellQuote(t.RemoteDir) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
ENV_DIR=` + ShellQuote(t.EnvDir()) + `
UNIT=` + ShellQuote(t.UnitPath()) + `

# The unit file, written atomically by the redirect.
cat > "$UNIT" <<'OTTER_UNIT_EOF'
`
	b.WriteString(script)
	b.WriteString(UnitFile(t))
	b.WriteString(`OTTER_UNIT_EOF
chmod 0644 "$UNIT"

# Lock down secrets before the daemon reads them, and opportunistically
# install the CLI wrapper for spot checks over SSH.
if [ -f "$REMOTE_DIR/bin/otter" ]; then
  chmod 0755 "$REMOTE_DIR/bin/otter"
  ln -sf "$REMOTE_DIR/bin/otter" /usr/local/bin/otter
fi
chmod 0600 "$ENV_DIR"/*.env 2>/dev/null || true

systemctl daemon-reload
systemctl enable "$SERVICE" >/dev/null 2>&1 || true
systemctl restart "$SERVICE"
`)
	return b.String()
}

// ServiceStatusScript reports whether the unit is active, then prints the tail
// of its journal so a failed start explains itself instead of timing out.
func ServiceStatusScript(t Target) string {
	return `SERVICE=` + ShellQuote(t.ServiceUnit()) + `
echo "unit: $(systemctl is-active "$SERVICE" 2>/dev/null || true)"
if ! systemctl is-active --quiet "$SERVICE"; then
  echo "--- last 25 journal lines ---"
  journalctl -u "$SERVICE" -n 25 --no-pager 2>/dev/null || true
  exit 1
fi
`
}

// ReleaseScript stages, prepares and activates a release for each integration
// on the host.
//
// It runs after the sources land and before the daemon restarts. Order matters
// twice over: preparation must not happen underneath a running attempt, and a
// failure here must leave the previous release active, which is why activation
// is the last thing `otter release` does rather than something this script
// performs.
//
// Shared code is not named here. Each manifest declares its own python.path,
// and the release captures exactly those trees at the depth the manifest
// resolves them at, so the layout lives in one place instead of being repeated
// on this command line.
//
// Integrations are named one by one rather than released with --all so each
// release reports its own failure against its own name in the deploy log.
func ReleaseScript(t Target, integrations []string, uvPath string) string {
	script := `set -e
RUN_AS=` + ShellQuote(t.RunAsUser) + `
REMOTE_DIR=` + ShellQuote(t.RemoteDir) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
CLI=` + ShellQuote(t.CLIPath()) + `
test -x "$CLI" || { echo "otter: missing $CLI" >&2; exit 1; }
# The data directory is prepared beforehand; releases only write inside it.
`

	runAs := ""
	if t.RunAsUser != "root" {
		script += `command -v runuser >/dev/null 2>&1 || { echo "otter: runuser is required to release as $RUN_AS" >&2; exit 1; }
`
		runAs = `runuser -u "$RUN_AS" -- `
	}

	for _, name := range integrations {
		command := runAs + `"$CLI" release` +
			" --integrations " + ShellQuote(t.IntegrationsDir()) +
			" --data " + ShellQuote(t.DataDir)
		if uvPath != "" {
			command += " --uv " + ShellQuote(uvPath)
		}
		command += " " + ShellQuote(name)

		script += "echo " + ShellQuote("releasing "+name) + "\n" + command + "\n"
	}
	// Each release reported success above, and a successful release is already
	// active; there is nothing further to switch.
	return script
}

// DestroyScript removes the unit and, unless keepData, the data directory.
// Losing the data directory means losing every integration's watermark, so the
// CLI requires an explicit flag before this runs without keeping it.
func DestroyScript(t Target, keepData bool) string {
	script := `set -e
SERVICE=` + ShellQuote(t.ServiceUnit()) + `
REMOTE_DIR=` + ShellQuote(t.RemoteDir) + `
DATA_DIR=` + ShellQuote(t.DataDir) + `
ENV_DIR=` + ShellQuote(t.EnvDir()) + `
UNIT=` + ShellQuote(t.UnitPath()) + `

systemctl stop "$SERVICE" 2>/dev/null || true
systemctl disable "$SERVICE" >/dev/null 2>&1 || true
rm -f "$UNIT"
rm -f /etc/systemd/system/multi-user.target.wants/"$SERVICE"
systemctl daemon-reload
systemctl reset-failed "$SERVICE" 2>/dev/null || true
rm -rf "$ENV_DIR"
`
	if !keepData {
		script += `rm -rf "$DATA_DIR"
`
	}
	script += `rm -rf "$REMOTE_DIR"
if [ -L /usr/local/bin/otter ]; then rm -f /usr/local/bin/otter; fi
`
	return script
}
